import PDFDocument from "pdfkit";

const COLORS = {
  heading: "#1f2328",
  subtle: "#59636e",
  accent: "#0969da",
  danger: "#cf222e",
};

function h1(doc, text) {
  doc.fontSize(18).fillColor(COLORS.heading).font("Helvetica-Bold").text(text);
  doc.moveDown(0.3);
}

function h2(doc, text) {
  doc.moveDown(0.6);
  doc.fontSize(13).fillColor(COLORS.heading).font("Helvetica-Bold").text(text);
  doc.moveDown(0.2);
}

function body(doc, text, opts = {}) {
  doc.fontSize(10).fillColor(opts.color ?? COLORS.heading).font("Helvetica").text(text, opts);
}

function bullet(doc, text) {
  doc.fontSize(10).fillColor(COLORS.heading).font("Helvetica").text(`•  ${text}`, { indent: 10 });
}

export function generateSummaryPDF(dailySummary, org = null) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const structured = dailySummary.structured ?? {};
    const repoName = dailySummary.repo_id?.full_name ?? dailySummary.repo_id?.name ?? "Repository";
    const periodLabel = structured.period_label ?? dailySummary.summary_type;
    const isAgency = org?.plan_tier === "agency";
    const brandTitle = isAgency ? (org.branding?.report_title || org.name) : null;
    const footerText = isAgency
      ? (org.branding?.footer_text || `${org.name} · Confidential`)
      : `Generated by GitPulse · ${new Date().toISOString()}`;

    if (brandTitle) {
      doc.fontSize(10).fillColor(COLORS.subtle).font("Helvetica").text(brandTitle.toUpperCase(), { align: "right" });
      doc.moveDown(0.5);
    }

    h1(doc, `${periodLabel} Report · ${repoName}`);
    const since = dailySummary.period?.since ? new Date(dailySummary.period.since) : null;
    const until = dailySummary.period?.until ? new Date(dailySummary.period.until) : null;
    if (since && until) {
      body(doc, `${since.toUTCString()} → ${until.toUTCString()}`, { color: COLORS.subtle });
    }
    body(
      doc,
      `${dailySummary.stats?.total_commits ?? 0} commits · ${dailySummary.stats?.contributors ?? 0} contributor(s)`,
      { color: COLORS.subtle }
    );

    if (structured.headline) {
      h2(doc, "Headline");
      body(doc, structured.headline);
    }

    if (structured.what_changed?.length) {
      h2(doc, "What Changed");
      structured.what_changed.forEach((item) => bullet(doc, item));
    }

    if (structured.why_it_matters) {
      h2(doc, "Impact");
      body(doc, structured.why_it_matters);
    }

    const byAuthor = structured.by_author ?? {};
    if (Object.keys(byAuthor).length) {
      h2(doc, "Contributors");
      for (const [author, commits] of Object.entries(byAuthor)) {
        doc.moveDown(0.3);
        doc.fontSize(10.5).fillColor(COLORS.accent).font("Helvetica-Bold")
          .text(`${author} — ${commits.length} commit${commits.length !== 1 ? "s" : ""}`);
        commits.forEach((c) => bullet(doc, `${c.message}  (${c.sha})`));
      }
    }

    if (structured.features?.length || structured.bug_fixes?.length || structured.chores?.length) {
      h2(doc, "Effort Breakdown");
      structured.features?.forEach((f) => bullet(doc, `Feature: ${f}`));
      structured.bug_fixes?.forEach((f) => bullet(doc, `Bug fix: ${f}`));
      structured.chores?.forEach((f) => bullet(doc, `Chore: ${f}`));
    }

    if (structured.has_blockers && structured.blockers?.length) {
      h2(doc, "Blockers");
      structured.blockers.forEach((b) => bullet(doc, b));
      if (structured.blocker_recommendation) {
        doc.moveDown(0.3);
        body(doc, `Recommendation: ${structured.blocker_recommendation}`, { color: COLORS.danger });
      }
    }

    doc.moveDown(1);
    doc.fontSize(8).fillColor(COLORS.subtle).font("Helvetica")
      .text(footerText, { align: "center" });

    doc.end();
  });
}
